### ISSUE TITLE
aktivacija plugina

### ISSUE THREAD

**Issue by deseliha** [marinsagovac/woocommerce-tcom-payway#11]
prilikom aktivacije plugina cijeli web site mi pokazuje gresku tj. ne prikazuje se vise. Postoji li neka postavka prije same aktivacije koja se mora promjeniti kako bi sve bilo ispravno i slagalo se sa web stranicom ? hvala

**Comment by marinsagovac** [comment]
Molim pogledajte uputstva: https://github.com/marinsagovac/woocommerce-tcom-payway/wiki

**Comment by marinsagovac** [comment]
Pozdrav,

objavljena je nova verzija https://github.com/marinsagovac/woocommerce-tcom-payway/releases/tag/1.5
