### ISSUE TITLE
[Feature request] Razdvojiti stranicu za callback od stranice za uspjeh i neuspjeh

### ISSUE THREAD

**Issue by shaxxx** [marinsagovac/woocommerce-tcom-payway#14]
Trenutno u postavkama plugina postoje 2 URL-a, jedan za uspjeh, jedan za neuspjeh.
Prema uputama ova dva URL-a bi trebala voditi na stranicu na kojoj je učitan plugin ( `domena.com/checkout`) kako bi se plugin učitao i obradio T-Com PayWay odgovor.
Kada se radi o neuspjehu plugin generira svoj HTML response koji obavještava da je došlo do greške i redirecta na url_fail nakon 3 sekunde. Tu je problem što to u principu korisniku prikaže vrlo kratko poruku i odvede ga na košaricu, osim toga poruka o grešci se ne može urediti. 
Još gora je situacija kada je riječ o uspjehu, korisnik se vrati na praznu košaricu i nema nikakve obavijesti o uspjehu.

Predlažem da se doda postavka "CallbackUrl" koja će biti kao dosadašnja `domena.com/checkout`.
T-Com PayWay bi i nakon uspjeha i nakon neuspjeha pozivao taj URL (koja bi posljedično pozvala `check_tcompayway_response()` funkciju.  Krajnji rezultat poziva ovoj funkciji i kod uspjeha i kod neuspjeha trebao bi biti wp_redirect poziv.
Kod uspjeha funkcija bi pozivala `response_url_success`, kod neuspjeha `response_url_fail`.
Na ovaj način T-Com bi uvijek pozivao callback url, što bi posljedično pozvalo funkciju `check_tcompayway_response()` koji bi odradio što i sada radi i na kraju pozvao URL za uspjeh ili neuspjeh.

Sada umjesto 
https://github.com/marinsagovac/woocommerce-tcom-payway/blob/0c0764c457855107ec378dea715c9734dfefc3d3/classes/class-wc-tpayway.php#L490
moram hardcodirati 
`wp_redirect('https://www.domena.com/vase-placanje-je-uspjesno/', 302);`
kako bi korisnik dobio obavijest da je plaćanje uspješno umjesto prazne košarice.

**Comment by shaxxx** [comment]
OK, sada nakon fixeva vidim da se callback `check_tcompayway_response` poziva na svim stranicama ne samo na checkout stranici. Problem je što callback nije radio ništa zbog ovih stvari za koje sam napravio PR.

**Comment by marinsagovac** [comment]
Objavljeno pod revision 1.5.
