### ISSUE TITLE
Problema estado de ventas

### ISSUE THREAD

**Issue by matijdk** [marinsagovac/woocommerce-tcom-payway#21]
Buenas tardes, tengo un problema con el estado de las ventas.... al cliente que realiza la compra les llega un email de payway de que dicha compra se realiza con exito, pero en mi woocommerce en pedidos la venta queda como "pendiente" , no como "completada".
Podrian ayudarme, ya que llame a la atenciontelefonica (3 numeros distintos), me hicieron enviar mails, y nadie sabe que decirme.
Muchas gracias, saludos.

**Comment by marinsagovac** [comment]
Please update latest plugin to [1.6](https://github.com/marinsagovac/woocommerce-tcom-payway/releases/tag/1.6) version.

You need approve from T-Com PayWay administration page (not from Wordpress) to set as "done" of payment.

Please checkout on PayWay administration page (not on Wordpress) just on PayWay HT administration page and see there of buyer status. Some users need to verify using token from mobile phone for processing (for example 3DES security). If they didn't do that, a status wil be pending until user manually pay or repeat action. You can revoke or pay again with 3DES that controlled by the bank.

Best regards,

**Comment by matijdk** [comment]
Hi! Thanks! how do i update it? just replacing the folder via ftp? i don´t going to lose all my settings?

**Comment by marinsagovac** [comment]
Hi!

Backup all settings somewhere in plain format if is needle or you can export backup settings in DB under `wp_options`.
I am not sure which version you have, you can try just replace it only folder.

A recommended way if is not working you can rename plugin name under wp-content/plugins/`myplugin` to `myplugin.disable`. Then upload as new folder to activate.

**Comment by matijdk** [comment]
yes, i allways rename the folder, is the way i do it. my version is 1.5. i will try to make a backup before as you say,i don´t know why the plugin have not an update form woocommerce.
i will try and then come back to here to comment.
thanks

**Comment by matijdk** [comment]
hi... i don´t know how do this from the DB. if i rename the folder and then replaece it for the new version 1.6.... whats folders have i to replace to for tray to keep my old configuration? Thanks

**Comment by marinsagovac** [comment]
Folder under wp-contents/plugins/woocommerce-tcom-payway to wp-contents/plugins/woocommerce-tcom-payway.disable

**Comment by matijdk** [comment]
Hola, no tenia tiempo, hoy lo hice, lo instale. No recuerdo en donde tengo que entrar para conseguir mi shoid y mi secrekey

**Comment by marinsagovac** [comment]
A secret key and shop ID are stored into your PayWay Hrvatski telekom site, https://administration.payway.com.hr/HR/Account/Login?ReturnUrl=%2fOn Oct 24, 2022 22:29, matijdk ***@***.***> wrote:
Hola, no tenia tiempo, hoy lo hice, lo instale. No recuerdo en donde tengo que entrar para conseguir mi shoid y mi secrekey
