### ISSUE TITLE
receipt_page action not firing

### ISSUE THREAD

**Issue by filipbudisa** [marinsagovac/woocommerce-tcom-payway#3]
On line 466, you define the payment method with the id "WC_TPAYWAY", but on line 57, you add the woocommerce_receipt_ action with the id "TPAYWAY", making the action not fire

**Comment by marinsagovac** [comment]
But you can find a method that will fire "receipt_page"  that find under current class. `woocommerce_receipt_TPAYWAY` is a tag name. A method is defined in a second argument of add_aciton() function. More info at https://developer.wordpress.org/reference/functions/add_action/#comment-354

**Comment by marinsagovac** [comment]
Fixed in release 1.1
