### ISSUE TITLE
typo in parameters

### ISSUE THREAD

**Issue by s28491** [marinsagovac/woocommerce-tcom-payway#7]
Hello,
I noticed typos regarding the Installments parameter in version 1.2 as well as in 1.3 release.

In version 1.2:

file tcom-payway-woocommerce.php,

line 239 it was:
`$pgwInstallments = '1'; ` (API says - `pgw_installments`).

line 337 it says:
`1000 => 'Neispravan potpis (pwg_signature)',` (should be 'pgw' instead of 'pwg').

---
In 1.3 release:

file classes/class-wc-tpayway.php, 

line 246 it says:
`$pwg_installments  = '1';` (should be 'pgw' instead of 'pwg')

line 349 it says:
`1000 => __( 'Incorrect signature (pwg_signature)', 'tcom-payway-wc' ),` (again, should be 'pgw' instead of 'pwg')

**Comment by marinsagovac** [comment]
Fixed params `pgw`: https://github.com/marinsagovac/woocommerce-tcom-payway/blob/master/classes/class-wc-tpayway.php

Signature already fixed.

Thanks.

Relesead: https://github.com/marinsagovac/woocommerce-tcom-payway/releases/tag/1.3.2
