### ISSUE TITLE
Gateway Description box does not show in the frontend on checkout

### ISSUE THREAD

**Issue by s28491** [marinsagovac/woocommerce-tcom-payway#8]
file `class-wc-tpayway.php:74`:

the content of the description field from the form_fields array does not show on frontend checkout when radio button is pressed.
Tried versions 1.2 and 1.3 simultaneously on the same webhsop, and the 1.2 one shows the box when the radio button is checked, 1.3 shows only the badges image banner.

**Comment by marinsagovac** [comment]
Fixed. It is not official published until you check it: https://github.com/marinsagovac/woocommerce-tcom-payway/releases/tag/1.3.2

Please review and feedback to me.
