### ISSUE TITLE
Syntax error in class WC_TPAYWAY

### ISSUE THREAD

**Issue by dmisljen** [marinsagovac/woocommerce-tcom-payway#9]
Hi,

You have a missing right parenthesis in: classes/class-wc-tpayway.php on line 26, which causes a fatal error while activating the plugin as-is.

**Comment by marinsagovac** [comment]
https://github.com/marinsagovac/woocommerce-tcom-payway/commit/6d7087f2d6ddd42a731d464e16734c1e1f77a4f5

Resolved.
